server:
    port: 8080
    contextPath: /toggl

###################################
#  PROFILE : LOCAL ON POSTGRES  #
###################################

---
spring:
  profiles: local
  data:
      mongodb:
        uri: mongodb://localhost:27017/toggl
