server:
    port: 8080
    contextPath: /toggl

###################################
#  PROFILE : LOCAL ON POSTGRES  #
###################################

---
spring:
  profiles: local
  jpa: 
    database: POSTGRESQL
    hibernate: 
      ddl-auto: none
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        hibernate.use-new-id-generator-mappings: true
    show-sql: false
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/insight
#    username: postgres
#    password: postgres
#    driverClassName: org.postgresql.Driver
